### ISSUE TITLE
can't run freeture with mode 2, 4 

### ISSUE THREAD

**Issue by yihahn** [fripon/freeture#13]
OS : Ubuntu 16.04
Freeture version : 1.0-4
X.org X Server version : 1.18.3
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

I entered below command in terminal, I got  an error message like this :

```
freeture -m 2 -d 0 -e 100 -g 300 --display
>>Error : boost:filesystem:create_directory: no such file or directory: "/home/fripon/data/"
freeture -m 4 -f 0 -d 0 -e 100 -g 300 --display
>>Error : boost:filesystem:create_directory: no such file or directory: "/home/fripon/data/"
```

even though freeture with mode 1 and 3 are working properly.

**Comment by cmarmo** [comment]
Hi yihahn,
It seems as the default `DATA_PATH` is used, set into the `/usr/share/freeture/configuration.cfg` file.
Could you try with the option `-c <path-to-your-config-file>`?
Thanks,
Chiara

**Comment by Asubayo** [comment]
If you want to use the default configuration file, change the value at DATA_PATH. The default value for this parameter is "/home/fripon/data/" but this directory doesn't exist on your system. Indeed, without -c option, the file from /usr/share/freeture/configuration.cfg is used.

**Comment by yihahn** [comment]
mode 2 and 4 work with -c option Thanks~!
