### ISSUE TITLE
Image custom size is not centered

### ISSUE THREAD

**Issue by ArkadiuszRaj** [fripon/freeture#17]
I just found that while using custom resolution, camera region is not programmed correctly. For circular fisheye lenses region shall be centered else this option is of no use. While centered, cpu consumption as well as ethernet bandwith is saved.

```
--- freeture/src/CameraGigeAravis.cpp   2016-06-28 17:19:59.585273406 +0200
+++ ../../freeture/src/CameraGigeAravis.cpp 2016-06-28 17:59:35.085035756 +0200
@@ -163,20 +163,19 @@

     bool CameraGigeAravis::setSize(int width, int height, bool customSize) {

-        if(customSize) {
+        int sensor_width, sensor_height;
+
+        arv_camera_get_sensor_size(camera, &sensor_width, &sensor_height);
+        BOOST_LOG_SEV(logger, notification) << "Camera sensor size : " << sensor_width << "x" << sensor_height;

-            arv_camera_set_region(camera, 0, 0,width,height);
+        if(customSize) {
+            arv_camera_set_region(camera, (sensor_width - width)/2, (sensor_height - height)/2,width,height);
             arv_camera_get_region (camera, NULL, NULL, &mWidth, &mHeight);
             BOOST_LOG_SEV(logger, notification) << "Camera region size : " << mWidth << "x" << mHeight;

         // Default is maximum size
         }else {

-            int sensor_width, sensor_height;
-
-            arv_camera_get_sensor_size(camera, &sensor_width, &sensor_height);
-            BOOST_LOG_SEV(logger, notification) << "Camera sensor size : " << sensor_width << "x" << sensor_height;
-
             arv_camera_set_region(camera, 0, 0,sensor_width,sensor_height);
             arv_camera_get_region (camera, NULL, NULL, &mWidth, &mHeight);
```

**Comment by cmarmo** [comment]
Hi Arkadiusz,
unfortunately, it is impossible to be sure that the useful region is centered on your detector. We have just implemented the basic function from aravis. In principle, you want to be able to define the pixel coordinates of four points on the detector, to be sure not to lose a piece of sky. This will ask a little bit more work and this is not planned for next developments.

**Comment by ArkadiuszRaj** [comment]
Camera having 1920x1200 with circular fisheye lens and defined region of 1600x1200 pixels produces such an image:
https://drive.google.com/open?id=0B5rxQmNJcvrBeEtHRVc1LWdUbEU

Well, what i was after is circular lens for which only centre of the image is useful. 

Linked image was produced by freeture with my correction.
