### ISSUE TITLE
OpenSuse fails to install Freeture

### ISSUE THREAD

**Issue by mpajuelo** [fripon/freeture#22]
I'm trying to install freeture in Opensuse 13.2
I already installed gstreamer 1.0

I can compile it but I got this message, could you help me?
(In what OS would you recommend me to install  freeture?)

g++  -g -O2   -o freeture EParser.o AcqThread.o CameraGigeAravis.o CameraGigePylon.o CameraV4l2.o CameraGigeTis.o CameraWindows.o DetectionTemplate.o DetectionTemporal.o Device.o Stack.o Ephemeris.o StackThread.o Base64.o OpenSSL.o CameraFrames.o SMTPClient.o HistogramGray.o CameraVideo.o Configuration.o Conversion.o DetThread.o Fits.o Fits2D.o Fits3D.o Frame.o GlobalEvent.o Histogram.o AcqSchedule.o LocalEvent.o main.o HistogramRGB.o TimeDate.o ExposureControl.o SaveImg.o ImgProcessing.o  -L/usr/local/lib64 -laravis-0.4 -lm -lgio-2.0 -lgobject-2.0 -lxml2 -lgthread-2.0 -pthread -lglib-2.0  -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -pthread -lgthread-2.0 -pthread -lglib-2.0 -lxml2  -lssl -lcrypto   -lcfitsio -L/usr/lib64 -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_video  -lboost_program_options -lboost_thread -lboost_system -lboost_log_setup -lboost_log -lboost_filesystem -lboost_date_time -lboost_chrono -lboost_iostreams -lv4l2  -lcrypto  -ludev  -lgobject-2.0 -lglib-2.0  -lglib-2.0  
/usr/lib64/libgstvideo-1.0.so.0: undefined reference to `gst_structure_get_flagset'
/usr/lib64/libgstvideo-1.0.so.0: undefined reference to`gst_flagset_register'
/usr/lib64/libgstaudio-1.0.so.0: undefined reference to `gst_segment_is_equal'
collect2: error: ld returned 1 exit status
Makefile:449: recipe for target 'freeture' failed
make[2]: **\* [freeture] Error 1
make[2]: Leaving directory '/usr

/local/src/freeture-1.0.1/src'
Makefile:491: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/freeture-1.0.1'
Makefile:406: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by cmarmo** [comment]
Hi mpajuelo,
a little bit late, I know... If you are still interested, I think 
`> sudo zypper install gstreamer-0_10-devel`
will solve your issue

Bests,
Chiara
