### ISSUE TITLE
Freeture in Windows

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#25]
Hi,

I have Fripon camera 171 ready to install, but I am having difficulty installing Freeture for Windows.  I attach a screenshot of the error message - I have not set the environment variable "PYLON_ROOT" in Windows 8.1.  Do you have setup instructions for Windows?  

Regards,

James Rowe

![camera171](https://cloud.githubusercontent.com/assets/20151919/19363694/60b644ac-9183-11e6-8733-26e1f0fe6463.jpg)
![pylonerror](https://cloud.githubusercontent.com/assets/20151919/19363695/60bed37e-9183-11e6-84c2-28d18d06718c.png)

**Comment by cmarmo** [comment]
Hi James,
Have you installed all necessary dependencies, in particular Pylon3? Take a look at this [wiki page](https://github.com/fripon/freeture/wiki/Visual-studio-2012-%28en%29)
Bests,
Chiara

**Comment by JRRowe** [comment]
Hi Chiara,

Thanks for your help, which I greatly appreciate.  I have now uninstalled Windows and have installed Debian.  As I am not familiar with Debian, I can install some packages (e.g. Teamviewer, Dropbox) but have been unable to install Pylon or Freeture.  I will keep trying to learn Debian!

Again thank you for your note, which I appreciate.

Regards,

Jim

**Comment by cmarmo** [comment]
Hi James,
Installation on Debian or Ubuntu is very straightforward. No need of pylon there. Just follow the instructions at [this page](https://github.com/fripon/freeture/wiki/Installing-FreeTure).

Bests,
Chiara

**Comment by JRRowe** [comment]
Hi Chiara,

Thanks.  I have tried this many times but I cannot make it install.  I will try again.

Regards,

Jim

**Comment by JRRowe** [comment]
Hi Chaira,

I get as far as “sh bootstrap.sh”, and then get this error:

Regards,

Jim

**Comment by cmarmo** [comment]
Hi James,
please, this is no more a Windows issue... :)
Could you open a new one with the debian error?
Thanks,
Chiara
