### ISSUE TITLE
"sh bootstrap.sh" fails during installation

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#26]
Hi,

I get part way through installation then get the error message shown in the bitmap, attached.

Regards, Jim Rowe

![freeture](https://cloud.githubusercontent.com/assets/20151919/20266534/6a45bab2-aa6e-11e6-9e81-eb96868a0f82.png)

**Comment by cmarmo** [comment]
Hi James,

`$ sudo apt-get install autotools`

Bests,
Chiara
