### ISSUE TITLE
config fails during installation

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#27]
Hi,

The installation is almost complete, but stops here:

![freeture](https://cloud.githubusercontent.com/assets/20151919/20268645/edf49e92-aa77-11e6-8224-fae895fd1269.png)

**Comment by ArkadiuszRaj** [comment]
sudo apt install  libudev-dev

**Comment by ArkadiuszRaj** [comment]
Or more general - all dependencies:

sudo apt install libudev-dev libssl-dev libboost-all-dev libcfitsio-dev

And do not forget about Aravis & OpenCV!

**Comment by JRRowe** [comment]
Thanks you, that is very helpful.  I have not forgotten about Aravis or OpenCV, but also I do not know how to get them.  Aravis is not in any repositories that I can discover.  I am finding it very, very difficult to install FreeTure, so thank you for your support!  Regards, Jim Rowe

**Comment by ArkadiuszRaj** [comment]
_For Aravis:_

**Prereqs:**

sudo apt-get install autoconf intltool libxml2-dev libtool gtk-doc-tools

get source from https://github.com/AravisProject/aravis/archive/ARAVIS_0_4_0.zip

**Compile**
cd aravis
./autogen.sh
make -j7 && sudo make install && sudo ldconfig

_For OpenCV_

**Prereqs:**
sudo apt install cmake build-essential libgtk2.0-dev 

Get source from https://github.com/opencv/opencv/archive/2.4.13.tar.gz 

**Compile**
cd opencv
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release  ../
make -j7 && sudo make install && sudo ldconfig

**Comment by JRRowe** [comment]
Thank you, that is much better.  I am closer!  However, please see below.  Installation still fails.  

![freeture](https://cloud.githubusercontent.com/assets/20151919/20321490/8783e748-ab6d-11e6-9c56-64231549a927.png)

**Comment by ArkadiuszRaj** [comment]
Yeap, another Freeture' dependency:

sudo apt install libv4l-dev

take a look at https://github.com/fripon/freeture/wiki/FreeTure-Dependencies

**Comment by JRRowe** [comment]
Thanks, but I get the message “unable to locate package libv41-dev”.  I am not being very clever I think…

**Comment by ArkadiuszRaj** [comment]
v4l - **V**ideo **F**or **L**inux

**Comment by JRRowe** [comment]
We are making progress.  Now I get the error below.  I tried to find a package called GST01 but can't.  

![freeture](https://cloud.githubusercontent.com/assets/20151919/20324437/84954422-ab78-11e6-9ee2-8bd566c9f29a.png)

**Comment by ArkadiuszRaj** [comment]
Which is libgstreamer0.10-dev

@cmarmo this one is not mentioned at the dependency page

**Comment by JRRowe** [comment]
Freeture is now made!  Fantastic!  But ... it gives an error as soon as it runs, do do with the Boost library - what have I done wrong?  Jim

![freeture](https://cloud.githubusercontent.com/assets/20151919/20326300/1d02fe14-ab80-11e6-897e-67661ecfae70.png)

**Comment by cmarmo** [comment]
@ArkadiuszRaj 

> this one is not mentioned at the dependency page

You're right, my mistake. But I'm rearranging dependences and packaging. I will fix it in the wiki or (better in the code see #28 ).

@JRRowe , you have a problem with the configuration file: please take a look at the [wiki configuration page](https://github.com/fripon/freeture/wiki/The%20configuration%20file), and start a new issue if needed.

Bests,
Chiara
