### ISSUE TITLE
Problem with FreeTure configuration

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#29]
Hi Chiara, you mentioned that this is a configuration issue (see screenshot below).  However, the file configuration.cfg doesn't mention the directory home/fripon/data or similar.  If I can't find the problem, I can't amend it.  I tried to attach the configuration.cfg file but github won't allow me to attach it.  

![freeture](https://cloud.githubusercontent.com/assets/20151919/20340022/63598d40-abd7-11e6-8c44-2ef0884d90f7.png)

**Comment by cmarmo** [comment]
Dear James,

please, pay attention to the documentation.
If you want to use your configuration file the command is 
`freeture -m 1 -c path_of_configuration_file`
or the default one will be taken.
This is detailed [here](https://github.com/fripon/freeture/wiki/Getting-started).
So now, breath and read the doc.

Bests,
Chiara

**Comment by JRRowe** [comment]
Thank you.  I have read the FreeTure Wiki over and over again since 20 October, and did not see that page before.  I appreciate your help on this.  

Once I have finished configuring FreeTure, I will temporarily swap out hard disks are run through the installation again on a fresh installation of Debian.  I will then send you my version of a step-by step installation guide, which includes all of the steps that you and your colleague have added.  I hope that this will be useful to you, and will help other users in future.  

Regards, Jim

**Comment by JRRowe** [comment]
Hi, I have spent another hour on this but it simply does not work.  To give you a break from my questions, I will spend another couple of days on it.  I won’t raise another query before Friday.  Jim
