### ISSUE TITLE
Feedback on improvements to FreeTure

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#32]
Francois Colas asked me to give feedback on possible improvements to Fripon, so here it is, attached as PDF.  I hope this is useful.  Regards, Jim Rowe

[Feedback on FreeTure 2016-12-30.pdf](https://github.com/fripon/freeture/files/702321/Feedback.on.FreeTure.2016-12-30.pdf)

**Comment by cmarmo** [comment]
Thanks. Could you please upload it on your github account as I can link it as External Resources on FreeTure wiki?

**Comment by JRRowe** [comment]
Thanks.  I tried but I get the message "Uploads are disabled. File uploads require push access to this repository."  I am a Github novice.

**Comment by cmarmo** [comment]
[External Resources page](https://github.com/fripon/freeture/wiki/External-Resources) now available on the FreeTure wiki.
