### ISSUE TITLE
User guide in English attached

### ISSUE THREAD

**Issue by JRRowe** [fripon/freeture#33]
I attach a user guide for FRIPON camera hardware using FreeTure for Windows.  This is intended to make it easier for a non-expert to get a camera running autonomously.  It is in English.  I hope it is useful.

[FreeTure Windows setup guide Ver 1.0.pdf](https://github.com/fripon/freeture/files/1151333/FreeTure.Windows.setup.guide.Ver.1.0.pdf)

**Comment by cmarmo** [comment]
Thanks for your work and for sharing it.
Could you please upload your documentation to you account as I can link it as External Resources in the FreeTure wiki?

**Comment by cmarmo** [comment]
[External Resources page](https://github.com/fripon/freeture/wiki/External-Resources) now available on the FreeTure wiki.
