### ISSUE TITLE
Freeture VS solution tutorial

### ISSUE THREAD

**Issue by dmna92** [fripon/freeture#5]
Hello,

I try to generate freeture with your tutorial in:
https://github.com/fripon/freeture/wiki/Visual-studio-2012-(fr).

when using Cmake i had to get openssl-0.9.8k_X64 to generate the VS solution
and i don't see it in the dependencies.

and when i try to generate the solution in VS  i didn't succeed and had 46 warnings and 13 errors

I can publish the log if you wish

Dominique

**Comment by Asubayo** [comment]
Hi Dominique,

Thanks for you note. Indeed, the wiki about building solution for VS2012 was not up to date. 
I corrected that by adding the missing part about openssl.

I also built a solution for VS2012. 
Yes there were some errors. I corrected them.
Can you try again to build a solution for VS2012 by getting the new freeture code ?

**Comment by dmna92** [comment]
Hi Yoan

I succeed to generate freeture with the change you made with only warnings.
I use the version of openssl you put in the tutorial and it help me a lot ;-).

I can't do no more because i don't have any of the cameras needed.

Now i try the linux version.
