### ISSUE TITLE
avi file creation with usb2 sd video grabber  and pal camera

### ISSUE THREAD

**Issue by dmna92** [fripon/freeture#7]
hello
i use freeture on on two stations: one with debian 64bits, one with windows7 64 bits with usb2 sd video grabber  and pal camera. 
in the configuration file, i put DET_SAVE_AVI to true but i have no avi file in case of détection on both station

Dominique

**Comment by Asubayo** [comment]
Hi Dominique,
Sorry for the delay.
Indeed, this parameters was disabled. It's now corrected. However, the generated .avi could be really black because the video's frames intensity are not "re-scaled".

Yoan
